config/routes.rb
Rails.application.routes.draw do

  root "reviews#index"
  resources :reviews
end

app/models/concerns/rotten_tomatoes.rb
module  RottenTomatoes
  API_KEY = Rails.application.secrets.rotten_tomatoes_key
  BASE_URL = "http://api.rottentomatoes.com/api/public/v1.0/"

  class MovieRequest

    attr_reader :id, :obj

    def initialize(params = {})
      if params[:q]
        @obj = JSON.parse(HTTParty.get("#{BASE_URL}movies?apikey=#{API_KEY}&q=#{params[:q]}"))["movies"].first
      elsif params[:id]
        @obj = JSON.parse(HTTParty.get("#{BASE_URL}movies/#{params[:id]}.json?apikey=#{API_KEY}"))
      elsif params[:url]
        @obj = JSON.parse(HTTParty.get(params[:url] + "?apikey=#{API_KEY}&page_limit=50"))
      end
      @id = @obj["id"]
    end


  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  include RottenTomatoes

  before_create :set_rt_data

  def freshness
    fresh? ? "fresh" : "rotten"
  end

  def rt_movie
    @rt_movie ||= RottenTomatoes::MovieRequest.new(id: rt_id).obj
  end

  def rt_reviews
    @rt_reviews ||= RottenTomatoes::MovieRequest.new(url: rt_movie["links"]["reviews"]).obj["reviews"]
  end

  def rt_similar
    @rt_similar ||= RottenTomatoes::MovieRequest.new(url: rt_movie["links"]["similar"]).obj
  end

  def adjusted_tomatometer
    total_freshness = rt_reviews.map{ |review| review["freshness"] }
    total_freshness << freshness
    fresh_reviews = total_freshness.select { |freshness| freshness if freshness == "fresh" }
    ((fresh_reviews.count.to_f / total_freshness.count.to_f) * 100).to_i
  end

  private

  def set_rt_data
    movie = RottenTomatoes::MovieRequest.new(q: title)
    self.rt_id =  movie.obj["id"]
    self.rt_poster_profile = movie.obj["posters"]["profile"]
    self.rt_poster_thumb = movie.obj["posters"]["thumbnail"]
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :get_review, only: [:show, :edit]

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:id, :title, :body, :fresh)
  end

  def get_review
    @review = Review.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MovieRev
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      = yield

app/views/reviews/_review_form.html.slim
=form_for(@review) do |f|
  = f.label :title
  = f.text_field :title, class: "form-control"
  = f.label :body
  = f.text_area :body, class: "form-control"
  = f.label :fresh
  = f.check_box :fresh, class: "form-control"
  = f.submit

app/views/reviews/index.html.slim
h1 Reviews
= link_to("Add Review", new_review_path, class: "btn-btn-success")

- @reviews.in_groups_of(12, false)do |group|
  .row
    - group.each do |review|
      .col-md-1 
        = link_to image_tag("#{review.rt_poster_thumb}"), review_path(review)
        h5 = review.title.titleize
        h6 = review.fresh? ? "Fresh!" : "Rotten!"

app/views/reviews/new.html.slim
h1 New Review
= render 'review_form'

app/views/reviews/show.html.slim
h1 = @review.title.titleize
article.jumbotron 
  = image_tag(@review.rt_poster_profile, size: "81x121.5", class: "review-img")
  = @review.body

.highlight
  p Adjusted Top Critic Tomatometer: #{@review.adjusted_tomatometer}%